#!/bin/bash

set -eu

cd $(dirname $0)/git-extensions
sudo -p "[sudo] password for $USER: " make install
cd - >> /dev/null
echo
echo "Installation successful. Type 'git help devbliss' to get started."
echo

