#!/bin/bash

set -eu

function is_repository_clean {
    if [ "`git status --short --untracked-files=no | wc -l | sed -e 's/ //g'`" != "0" ]; then
        return 1
    fi
    return 0
}

latest_remote=$(github-devbliss tags | sort --version-sort | tail -n1)
cd $(dirname $0)/git-extensions
git fetch origin --quiet
git fetch origin --tags --quiet
stashed=0
if ! is_repository_clean; then
    git stash >> /dev/null
    stashed=1
fi
git checkout --quiet $latest_remote
sudo -p "[sudo] password for $USER: " make install
cd - >> /dev/null
git checkout --quiet -
if [[ $stashed = 1 ]]; then
    git stash apply >> /dev/null
fi
echo
echo "Update successful. You're now on version $latest_remote"
echo
#What's new?
changelog="/usr/share/doc/git-devbliss/CHANGES.md"
perl -pe '/^#+ +\d\.\d\.\d([^\.].*)?$/ && $entry++; if ($entry > 1) {exit};' $changelog
